//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFSeguridad
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sistema", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemasService")]
    public partial class Sistema : object
    {
        
        private string ID_Codigo_generado_ploneField;
        
        private string ID_SistemaField;
        
        private string IP_RemotoField;
        
        private string Nombre_exploradorField;
        
        private string Nombre_pagina_webField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Codigo_generado_plone
        {
            get
            {
                return this.ID_Codigo_generado_ploneField;
            }
            set
            {
                this.ID_Codigo_generado_ploneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Sistema
        {
            get
            {
                return this.ID_SistemaField;
            }
            set
            {
                this.ID_SistemaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP_Remoto
        {
            get
            {
                return this.IP_RemotoField;
            }
            set
            {
                this.IP_RemotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_explorador
        {
            get
            {
                return this.Nombre_exploradorField;
            }
            set
            {
                this.Nombre_exploradorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_pagina_web
        {
            get
            {
                return this.Nombre_pagina_webField;
            }
            set
            {
                this.Nombre_pagina_webField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddSistemaResult", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemasService")]
    public partial class AddSistemaResult : object
    {
        
        private string CoduserField;
        
        private string FechaField;
        
        private string FullnameField;
        
        private string MensajeField;
        
        private WCFSeguridad.MenuSistema MenuSistemaField;
        
        private string PasswordField;
        
        private string ResponsableCorreoField;
        
        private string ResponsableDireccionField;
        
        private string ResponsableNombreField;
        
        private string ResponsablePrimerApellidoField;
        
        private string ResponsableSegundoApellidoField;
        
        private string ReturnCodeField;
        
        private string RolField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Coduser
        {
            get
            {
                return this.CoduserField;
            }
            set
            {
                this.CoduserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fullname
        {
            get
            {
                return this.FullnameField;
            }
            set
            {
                this.FullnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFSeguridad.MenuSistema MenuSistema
        {
            get
            {
                return this.MenuSistemaField;
            }
            set
            {
                this.MenuSistemaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsableCorreo
        {
            get
            {
                return this.ResponsableCorreoField;
            }
            set
            {
                this.ResponsableCorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsableDireccion
        {
            get
            {
                return this.ResponsableDireccionField;
            }
            set
            {
                this.ResponsableDireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsableNombre
        {
            get
            {
                return this.ResponsableNombreField;
            }
            set
            {
                this.ResponsableNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsablePrimerApellido
        {
            get
            {
                return this.ResponsablePrimerApellidoField;
            }
            set
            {
                this.ResponsablePrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsableSegundoApellido
        {
            get
            {
                return this.ResponsableSegundoApellidoField;
            }
            set
            {
                this.ResponsableSegundoApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnCode
        {
            get
            {
                return this.ReturnCodeField;
            }
            set
            {
                this.ReturnCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rol
        {
            get
            {
                return this.RolField;
            }
            set
            {
                this.RolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuSistema", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemasService")]
    public partial class MenuSistema : object
    {
        
        private string DES_ABREV_SISField;
        
        private string DES_ESQUEMAField;
        
        private string DES_OPCIONField;
        
        private string DES_SISTEMAField;
        
        private string DES_URLField;
        
        private string DES_URLIMAGENField;
        
        private long ID_SISField;
        
        private string NUM_NIVELField;
        
        private string NUM_ORDENField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_ABREV_SIS
        {
            get
            {
                return this.DES_ABREV_SISField;
            }
            set
            {
                this.DES_ABREV_SISField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_ESQUEMA
        {
            get
            {
                return this.DES_ESQUEMAField;
            }
            set
            {
                this.DES_ESQUEMAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_OPCION
        {
            get
            {
                return this.DES_OPCIONField;
            }
            set
            {
                this.DES_OPCIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_SISTEMA
        {
            get
            {
                return this.DES_SISTEMAField;
            }
            set
            {
                this.DES_SISTEMAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_URL
        {
            get
            {
                return this.DES_URLField;
            }
            set
            {
                this.DES_URLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_URLIMAGEN
        {
            get
            {
                return this.DES_URLIMAGENField;
            }
            set
            {
                this.DES_URLIMAGENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID_SIS
        {
            get
            {
                return this.ID_SISField;
            }
            set
            {
                this.ID_SISField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUM_NIVEL
        {
            get
            {
                return this.NUM_NIVELField;
            }
            set
            {
                this.NUM_NIVELField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUM_ORDEN
        {
            get
            {
                return this.NUM_ORDENField;
            }
            set
            {
                this.NUM_ORDENField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFSeguridad.IWCFSistemasService")]
    public interface IWCFSistemasService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/AddSistema", ReplyAction="http://tempuri.org/IWCFSistemasService/AddSistemaResponse")]
        WCFSeguridad.AddSistemaResult AddSistema(WCFSeguridad.Sistema Sistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/AddSistema", ReplyAction="http://tempuri.org/IWCFSistemasService/AddSistemaResponse")]
        System.Threading.Tasks.Task<WCFSeguridad.AddSistemaResult> AddSistemaAsync(WCFSeguridad.Sistema Sistema);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IWCFSistemasServiceChannel : WCFSeguridad.IWCFSistemasService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class WCFSistemasServiceClient : System.ServiceModel.ClientBase<WCFSeguridad.IWCFSistemasService>, WCFSeguridad.IWCFSistemasService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WCFSistemasServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(WCFSistemasServiceClient.GetBindingForEndpoint(endpointConfiguration), WCFSistemasServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WCFSistemasServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WCFSistemasServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WCFSistemasServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WCFSistemasServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WCFSistemasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public WCFSeguridad.AddSistemaResult AddSistema(WCFSeguridad.Sistema Sistema)
        {
            return base.Channel.AddSistema(Sistema);
        }
        
        public System.Threading.Tasks.Task<WCFSeguridad.AddSistemaResult> AddSistemaAsync(WCFSeguridad.Sistema Sistema)
        {
            return base.Channel.AddSistemaAsync(Sistema);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWCFSistemasService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IWCFSistemasService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWCFSistemasService))
            {
                return new System.ServiceModel.EndpointAddress("http://vservicios/ServicioAcceso2/WCFSistemasService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IWCFSistemasService))
            {
                return new System.ServiceModel.EndpointAddress("https://vservicios.mem.int/ServicioAcceso2/WCFSistemasService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWCFSistemasService,
            
            BasicHttpsBinding_IWCFSistemasService,
        }
    }
}
