//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minem.Sgpam.WebApiLF.WCFSeguridad {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sistema", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemasService")]
    [System.SerializableAttribute()]
    public partial class Sistema : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_Codigo_generado_ploneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_SistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IP_RemotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_exploradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_pagina_webField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Codigo_generado_plone {
            get {
                return this.ID_Codigo_generado_ploneField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_Codigo_generado_ploneField, value) != true)) {
                    this.ID_Codigo_generado_ploneField = value;
                    this.RaisePropertyChanged("ID_Codigo_generado_plone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Sistema {
            get {
                return this.ID_SistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_SistemaField, value) != true)) {
                    this.ID_SistemaField = value;
                    this.RaisePropertyChanged("ID_Sistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP_Remoto {
            get {
                return this.IP_RemotoField;
            }
            set {
                if ((object.ReferenceEquals(this.IP_RemotoField, value) != true)) {
                    this.IP_RemotoField = value;
                    this.RaisePropertyChanged("IP_Remoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_explorador {
            get {
                return this.Nombre_exploradorField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_exploradorField, value) != true)) {
                    this.Nombre_exploradorField = value;
                    this.RaisePropertyChanged("Nombre_explorador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_pagina_web {
            get {
                return this.Nombre_pagina_webField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_pagina_webField, value) != true)) {
                    this.Nombre_pagina_webField = value;
                    this.RaisePropertyChanged("Nombre_pagina_web");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddSistemaResult", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemasService")]
    [System.SerializableAttribute()]
    public partial class AddSistemaResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoduserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Minem.Sgpam.WebApiLF.WCFSeguridad.MenuSistema MenuSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsableCorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsableDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsableNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsablePrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsableSegundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Coduser {
            get {
                return this.CoduserField;
            }
            set {
                if ((object.ReferenceEquals(this.CoduserField, value) != true)) {
                    this.CoduserField = value;
                    this.RaisePropertyChanged("Coduser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fullname {
            get {
                return this.FullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullnameField, value) != true)) {
                    this.FullnameField = value;
                    this.RaisePropertyChanged("Fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Minem.Sgpam.WebApiLF.WCFSeguridad.MenuSistema MenuSistema {
            get {
                return this.MenuSistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuSistemaField, value) != true)) {
                    this.MenuSistemaField = value;
                    this.RaisePropertyChanged("MenuSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsableCorreo {
            get {
                return this.ResponsableCorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsableCorreoField, value) != true)) {
                    this.ResponsableCorreoField = value;
                    this.RaisePropertyChanged("ResponsableCorreo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsableDireccion {
            get {
                return this.ResponsableDireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsableDireccionField, value) != true)) {
                    this.ResponsableDireccionField = value;
                    this.RaisePropertyChanged("ResponsableDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsableNombre {
            get {
                return this.ResponsableNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsableNombreField, value) != true)) {
                    this.ResponsableNombreField = value;
                    this.RaisePropertyChanged("ResponsableNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsablePrimerApellido {
            get {
                return this.ResponsablePrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsablePrimerApellidoField, value) != true)) {
                    this.ResponsablePrimerApellidoField = value;
                    this.RaisePropertyChanged("ResponsablePrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsableSegundoApellido {
            get {
                return this.ResponsableSegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsableSegundoApellidoField, value) != true)) {
                    this.ResponsableSegundoApellidoField = value;
                    this.RaisePropertyChanged("ResponsableSegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnCode {
            get {
                return this.ReturnCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnCodeField, value) != true)) {
                    this.ReturnCodeField = value;
                    this.RaisePropertyChanged("ReturnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuSistema", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemasService")]
    [System.SerializableAttribute()]
    public partial class MenuSistema : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_ABREV_SISField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_ESQUEMAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_OPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_SISTEMAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_URLIMAGENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ID_SISField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_NIVELField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_ORDENField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_ABREV_SIS {
            get {
                return this.DES_ABREV_SISField;
            }
            set {
                if ((object.ReferenceEquals(this.DES_ABREV_SISField, value) != true)) {
                    this.DES_ABREV_SISField = value;
                    this.RaisePropertyChanged("DES_ABREV_SIS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_ESQUEMA {
            get {
                return this.DES_ESQUEMAField;
            }
            set {
                if ((object.ReferenceEquals(this.DES_ESQUEMAField, value) != true)) {
                    this.DES_ESQUEMAField = value;
                    this.RaisePropertyChanged("DES_ESQUEMA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_OPCION {
            get {
                return this.DES_OPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DES_OPCIONField, value) != true)) {
                    this.DES_OPCIONField = value;
                    this.RaisePropertyChanged("DES_OPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_SISTEMA {
            get {
                return this.DES_SISTEMAField;
            }
            set {
                if ((object.ReferenceEquals(this.DES_SISTEMAField, value) != true)) {
                    this.DES_SISTEMAField = value;
                    this.RaisePropertyChanged("DES_SISTEMA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_URL {
            get {
                return this.DES_URLField;
            }
            set {
                if ((object.ReferenceEquals(this.DES_URLField, value) != true)) {
                    this.DES_URLField = value;
                    this.RaisePropertyChanged("DES_URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_URLIMAGEN {
            get {
                return this.DES_URLIMAGENField;
            }
            set {
                if ((object.ReferenceEquals(this.DES_URLIMAGENField, value) != true)) {
                    this.DES_URLIMAGENField = value;
                    this.RaisePropertyChanged("DES_URLIMAGEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID_SIS {
            get {
                return this.ID_SISField;
            }
            set {
                if ((this.ID_SISField.Equals(value) != true)) {
                    this.ID_SISField = value;
                    this.RaisePropertyChanged("ID_SIS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUM_NIVEL {
            get {
                return this.NUM_NIVELField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_NIVELField, value) != true)) {
                    this.NUM_NIVELField = value;
                    this.RaisePropertyChanged("NUM_NIVEL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUM_ORDEN {
            get {
                return this.NUM_ORDENField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_ORDENField, value) != true)) {
                    this.NUM_ORDENField = value;
                    this.RaisePropertyChanged("NUM_ORDEN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFSeguridad.IWCFSistemasService")]
    public interface IWCFSistemasService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/AddSistema", ReplyAction="http://tempuri.org/IWCFSistemasService/AddSistemaResponse")]
        Minem.Sgpam.WebApiLF.WCFSeguridad.AddSistemaResult AddSistema(Minem.Sgpam.WebApiLF.WCFSeguridad.Sistema Sistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/AddSistema", ReplyAction="http://tempuri.org/IWCFSistemasService/AddSistemaResponse")]
        System.Threading.Tasks.Task<Minem.Sgpam.WebApiLF.WCFSeguridad.AddSistemaResult> AddSistemaAsync(Minem.Sgpam.WebApiLF.WCFSeguridad.Sistema Sistema);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFSistemasServiceChannel : Minem.Sgpam.WebApiLF.WCFSeguridad.IWCFSistemasService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFSistemasServiceClient : System.ServiceModel.ClientBase<Minem.Sgpam.WebApiLF.WCFSeguridad.IWCFSistemasService>, Minem.Sgpam.WebApiLF.WCFSeguridad.IWCFSistemasService {
        
        public WCFSistemasServiceClient() {
        }
        
        public WCFSistemasServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFSistemasServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFSistemasServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFSistemasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Minem.Sgpam.WebApiLF.WCFSeguridad.AddSistemaResult AddSistema(Minem.Sgpam.WebApiLF.WCFSeguridad.Sistema Sistema) {
            return base.Channel.AddSistema(Sistema);
        }
        
        public System.Threading.Tasks.Task<Minem.Sgpam.WebApiLF.WCFSeguridad.AddSistemaResult> AddSistemaAsync(Minem.Sgpam.WebApiLF.WCFSeguridad.Sistema Sistema) {
            return base.Channel.AddSistemaAsync(Sistema);
        }
    }
}
