CREATE SEQUENCE SEQ_T_SGPAL_TIPO_OPERACION START WITH 1;

CREATE OR REPLACE TRIGGER TGR_T_SGPAL_TIPO_OPERACION
BEFORE INSERT ON T_SGPAL_TIPO_OPERACION
FOR EACH ROW

BEGIN
  SELECT SEQ_T_SGPAL_TIPO_OPERACION.NEXTVAL
  INTO   :new.ID_TIPO_OPERACION
  FROM   dual;
END;

	 
CREATE SEQUENCE SEQ_T_SGPAD_COMP_COMENTARIO START WITH 1;

CREATE OR REPLACE TRIGGER TGR_T_SGPAD_COMP_COMENTARIO
BEFORE INSERT ON T_SGPAD_COMP_COMENTARIO
FOR EACH ROW
BEGIN
  SELECT SEQ_T_SGPAD_COMP_COMENTARIO.NEXTVAL
  INTO   :new.ID_COMP_COMENTARIO
  FROM   dual;
END;


CREATE SEQUENCE SEQ_T_SGPAD_COMP_MEDICION START WITH 1;

CREATE OR REPLACE TRIGGER TGR_T_SGPAD_COMP_MEDICION
BEFORE INSERT ON T_SGPAD_COMP_MEDICION
FOR EACH ROW
BEGIN
  SELECT SEQ_T_SGPAD_COMP_MEDICION.NEXTVAL
  INTO   :new.ID_COMP_MEDICION
  FROM   dual;
END;



CREATE SEQUENCE SEQ_T_SGPAD_COMP_REAPRO START WITH 1;

CREATE OR REPLACE TRIGGER TGR_T_SGPAD_COMP_REAPRO
BEFORE INSERT ON T_SGPAD_COMP_REAPRO
FOR EACH ROW
BEGIN
  SELECT SEQ_T_SGPAD_COMP_REAPRO.NEXTVAL
  INTO   :new.ID_COMP_REAPRO
  FROM   dual;
END;


CREATE SEQUENCE SEQ_T_SGPAD_COMP_INFO_CAMPO START WITH 1;

CREATE OR REPLACE TRIGGER TGR_T_SGPAD_COMP_INFO_CAMPO
BEFORE INSERT ON T_SGPAD_COMP_INFO_CAMPO
FOR EACH ROW
BEGIN
  SELECT SEQ_T_SGPAD_COMP_INFO_CAMPO.NEXTVAL
  INTO   :new.ID_COMP_INFO_CAMPO
  FROM   dual;
END;


CREATE SEQUENCE SEQ_T_SGPAD_COMP_RECONOCIMIENT START WITH 1;

CREATE OR REPLACE TRIGGER TGR_T_SGPAD_COMP_RECONOCIMIENT
BEFORE INSERT ON T_SGPAD_COMP_RECONOCIMIENTO
FOR EACH ROW
BEGIN
  SELECT SEQ_T_SGPAD_COMP_RECONOCIMIENT.NEXTVAL
  INTO   :new.ID_COMP_RECONOCIMIENTO
  FROM   dual;
END;


CREATE SEQUENCE SEQ_T_SGPAD_COMP_RIESGO_SEG_HU START WITH 1;

CREATE OR REPLACE TRIGGER TGR_T_SGPAD_COMP_RIESGO_SEG_HU
BEFORE INSERT ON T_SGPAD_COMP_RIESGO_SEG_HUM
FOR EACH ROW
BEGIN
  SELECT SEQ_T_SGPAD_COMP_RIESGO_SEG_HU.NEXTVAL
  INTO   :new.ID_COMP_RIESGO_SEG_HUM
  FROM   dual;
END;


CREATE SEQUENCE SEQ_T_SGPAD_COMP_RIESGO_SAL_AM START WITH 1;

CREATE OR REPLACE TRIGGER TGR_T_SGPAD_COMP_RIESGO_SAL_AM
BEFORE INSERT ON T_SGPAD_COMP_RIESGO_SAL_AMB
FOR EACH ROW
BEGIN
  SELECT SEQ_T_SGPAD_COMP_RIESGO_SAL_AM.NEXTVAL
  INTO   :new.ID_COMP_RIESGO_SAL_AMB
  FROM   dual;
END;



CREATE SEQUENCE SEQ_T_SGPAD_COMP_RIESGO_FAU_CO START WITH 1;

CREATE OR REPLACE TRIGGER TGR_T_SGPAD_COMP_RIESGO_FAU_CO
BEFORE INSERT ON T_SGPAD_COMP_RIESGO_FAU_CON
FOR EACH ROW
BEGIN
  SELECT SEQ_T_SGPAD_COMP_RIESGO_FAU_CO.NEXTVAL
  INTO   :new.ID_COMP_RIESGO_FAU_CON
  FROM   dual;
END;


CREATE SEQUENCE SEQ_T_SGPAD_COMP_ENC_REM START WITH 1;

CREATE OR REPLACE TRIGGER TGR_T_SGPAD_COMP_ENC_REM
BEFORE INSERT ON T_SGPAD_COMP_ENC_REM
FOR EACH ROW
BEGIN
  SELECT SEQ_T_SGPAD_COMP_ENC_REM.NEXTVAL
  INTO   :new.ID_COMP_ENC_REM
  FROM   dual;
END;


CREATE SEQUENCE SEQ_T_SGPAD_COMP_INFO_GRAFICA START WITH 1;

CREATE OR REPLACE TRIGGER TGR_T_SGPAD_COMP_INFO_GRAFICA
BEFORE INSERT ON T_SGPAD_COMP_INFO_GRAFICA
FOR EACH ROW
BEGIN
  SELECT SEQ_T_SGPAD_COMP_INFO_GRAFICA.NEXTVAL
  INTO   :new.ID_COMP_INFO_GRAFICA
  FROM   dual;
END;


CREATE SEQUENCE SEQ_T_SGPAH_COMPONENTE_MOD START WITH 1;

CREATE OR REPLACE TRIGGER TGR_T_SGPAH_COMPONENTE_MOD
BEFORE INSERT ON T_SGPAH_COMPONENTE_MOD
FOR EACH ROW
BEGIN
  SELECT SEQ_T_SGPAH_COMPONENTE_MOD.NEXTVAL
  INTO   :new.ID_COMPONENTE_MOD
  FROM   dual;
END;


CREATE SEQUENCE SEQ_T_SGPAD_COMP_RESULTADO START WITH 1;

CREATE OR REPLACE TRIGGER TGR_T_SGPAD_COMP_RESULTADO
BEFORE INSERT ON T_SGPAD_COMP_RESULTADO
FOR EACH ROW
BEGIN
  SELECT SEQ_T_SGPAD_COMP_RESULTADO.NEXTVAL
  INTO   :new.ID_COMP_RESULTADO
  FROM   dual;
END;


CREATE SEQUENCE SEQ_T_SGPAD_COMP_EST_AMB START WITH 1;

CREATE OR REPLACE TRIGGER TGR_T_SGPAD_COMP_EST_AMB
BEFORE INSERT ON T_SGPAD_COMP_EST_AMB
FOR EACH ROW
BEGIN
  SELECT SEQ_T_SGPAD_COMP_EST_AMB.NEXTVAL
  INTO   :new.ID_COMP_EST_AMB
  FROM   dual;
END;
  
  
CREATE SEQUENCE SEQ_T_SGPAD_COMP_EST_GESTION START WITH 1;

CREATE OR REPLACE TRIGGER TGR_T_SGPAD_COMP_EST_GESTION
BEFORE INSERT ON T_SGPAD_COMP_EST_GESTION
FOR EACH ROW
BEGIN
  SELECT SEQ_T_SGPAD_COMP_EST_GESTION.NEXTVAL
  INTO   :new.ID_COMP_EST_GESTION
  FROM   dual;
END;



--SELECT * FROM T_SGPAD_COMPONENTE

Insert into SIGEPAM.T_SGPAD_COMPONENTE (ID_COMPONENTE,ID_EUM,NOMBRE,ID_TIPO_PAM,ID_SUB_TIPO_PAM,OTRO_DESCRIPCION,ESTE,NORTE,ID_ZONA,ID_DATUM,UBICACION,DESCRIPCION,ID_CUENCA_HIDRO,UBIGEO,ID_CUENCA,ID_CUENCA_SECUNDARIA,ID_TIPO_MINERIA,ID_TAMANO_PARTICULA,ID_HUMEDAD,ID_TIPO_CONCESION,ID_COBERTURA,CARACTERISTICA,PUNTAJE,PUNTAJE_NORMALIZADO,ID_SITUACION_PAM,USU_INGRESO,FEC_INGRESO,IP_INGRESO,USU_MODIFICA,FEC_MODIFICA,IP_MODIFICA,FLG_ESTADO,RIESGO) values ('1','0','NOMBRE INFRAESTRUCTURA','4','22','NOCHE CALIENTE','87','124','20','Datum_B','PLANETA TIERRA',' PRUEBA NOVIEMBRE','1','150302','1',null,null,null,null,null,null,null,'42','82',null,'ORODRIGUEZ',to_date('16/11/21','DD/MM/RR'),'MIPC','FULLSHITO',to_date('16/11/21','DD/MM/RR'),null,'1','MUY ALTO');
Insert into SIGEPAM.T_SGPAD_COMPONENTE (ID_COMPONENTE,ID_EUM,NOMBRE,ID_TIPO_PAM,ID_SUB_TIPO_PAM,OTRO_DESCRIPCION,ESTE,NORTE,ID_ZONA,ID_DATUM,UBICACION,DESCRIPCION,ID_CUENCA_HIDRO,UBIGEO,ID_CUENCA,ID_CUENCA_SECUNDARIA,ID_TIPO_MINERIA,ID_TAMANO_PARTICULA,ID_HUMEDAD,ID_TIPO_CONCESION,ID_COBERTURA,CARACTERISTICA,PUNTAJE,PUNTAJE_NORMALIZADO,ID_SITUACION_PAM,USU_INGRESO,FEC_INGRESO,IP_INGRESO,USU_MODIFICA,FEC_MODIFICA,IP_MODIFICA,FLG_ESTADO,RIESGO) values ('2','0','NOMBRE LABOR MINERA','1','4','NOCHE HELADA','87','124','20','Datum_B','PLANETA TIERRA',' PRUEBA DICIEMBRER','1','150302','1',null,null,null,null,null,null,null,'16','31',null,'ORODRIGUEZ',to_date('16/11/21','DD/MM/RR'),'MIPC','FULLSHITO',to_date('16/11/21','DD/MM/RR'),null,'1','BAJO');
Insert into SIGEPAM.T_SGPAD_COMPONENTE (ID_COMPONENTE,ID_EUM,NOMBRE,ID_TIPO_PAM,ID_SUB_TIPO_PAM,OTRO_DESCRIPCION,ESTE,NORTE,ID_ZONA,ID_DATUM,UBICACION,DESCRIPCION,ID_CUENCA_HIDRO,UBIGEO,ID_CUENCA,ID_CUENCA_SECUNDARIA,ID_TIPO_MINERIA,ID_TAMANO_PARTICULA,ID_HUMEDAD,ID_TIPO_CONCESION,ID_COBERTURA,CARACTERISTICA,PUNTAJE,PUNTAJE_NORMALIZADO,ID_SITUACION_PAM,USU_INGRESO,FEC_INGRESO,IP_INGRESO,USU_MODIFICA,FEC_MODIFICA,IP_MODIFICA,FLG_ESTADO,RIESGO) values ('3','0','NOMBRE OTROS RESIDUOS','3','19','NOCHE FRIA','87','124','20','Datum_B','PLANETA TIERRA',' ENFERMO ENERO','1','150302','1',null,null,null,null,null,null,null,'16','31',null,'ORODRIGUEZ',to_date('16/11/21','DD/MM/RR'),'MIPC','FULLSHITO',to_date('16/11/21','DD/MM/RR'),null,'1','BAJO');
Insert into SIGEPAM.T_SGPAD_COMPONENTE (ID_COMPONENTE,ID_EUM,NOMBRE,ID_TIPO_PAM,ID_SUB_TIPO_PAM,OTRO_DESCRIPCION,ESTE,NORTE,ID_ZONA,ID_DATUM,UBICACION,DESCRIPCION,ID_CUENCA_HIDRO,UBIGEO,ID_CUENCA,ID_CUENCA_SECUNDARIA,ID_TIPO_MINERIA,ID_TAMANO_PARTICULA,ID_HUMEDAD,ID_TIPO_CONCESION,ID_COBERTURA,CARACTERISTICA,PUNTAJE,PUNTAJE_NORMALIZADO,ID_SITUACION_PAM,USU_INGRESO,FEC_INGRESO,IP_INGRESO,USU_MODIFICA,FEC_MODIFICA,IP_MODIFICA,FLG_ESTADO,RIESGO) values ('4','0','NOMBRE RESIDUOS MINEROS','2','13','NOCHE COVID','87','124','20','Datum_B','PLANETA TIERRA',' ENFERMO ENERO','1','150302','1',null,null,null,null,null,null,null,'16','31',null,'ORODRIGUEZ',to_date('16/11/21','DD/MM/RR'),'MIPC','FULLSHITO',to_date('16/11/21','DD/MM/RR'),null,'1','BAJO');
Insert into SIGEPAM.T_SGPAD_COMPONENTE (ID_COMPONENTE,ID_EUM,NOMBRE,ID_TIPO_PAM,ID_SUB_TIPO_PAM,OTRO_DESCRIPCION,ESTE,NORTE,ID_ZONA,ID_DATUM,UBICACION,DESCRIPCION,ID_CUENCA_HIDRO,UBIGEO,ID_CUENCA,ID_CUENCA_SECUNDARIA,ID_TIPO_MINERIA,ID_TAMANO_PARTICULA,ID_HUMEDAD,ID_TIPO_CONCESION,ID_COBERTURA,CARACTERISTICA,PUNTAJE,PUNTAJE_NORMALIZADO,ID_SITUACION_PAM,USU_INGRESO,FEC_INGRESO,IP_INGRESO,USU_MODIFICA,FEC_MODIFICA,IP_MODIFICA,FLG_ESTADO,RIESGO) values ('5','0','NOMBRE SUSTANCIA QUIMICAS','5','30','DIA DEL OMICROM O DELTA','87','124','20','Datum_B','PLANETA TIERRA',' ENFERMO ENERO','1','150302','1',null,null,null,null,null,null,null,'10','20',null,'ORODRIGUEZ',to_date('16/11/21','DD/MM/RR'),'MIPC','FULLSHITO',to_date('16/11/21','DD/MM/RR'),null,'1','INSIGNIFICANTE');




--Insert into SIGEPAM.T_SGPAD_COMPONENTE (ID_EUM,NOMBRE,ID_TIPO_PAM,ID_SUB_TIPO_PAM,OTRO_DESCRIPCION,ESTE,NORTE,ID_ZONA,ID_DATUM,UBICACION,DESCRIPCION,ID_CUENCA_HIDRO,UBIGEO,ID_CUENCA,ID_CUENCA_SECUNDARIA,ID_TIPO_MINERIA,ID_TAMANO_PARTICULA,ID_HUMEDAD,ID_TIPO_CONCESION,ID_COBERTURA,CARACTERISTICA,PUNTAJE,PUNTAJE_NORMALIZADO,ID_SITUACION_PAM,USU_INGRESO,FEC_INGRESO,IP_INGRESO,USU_MODIFICA,FEC_MODIFICA,IP_MODIFICA,FLG_ESTADO,RIESGO) values ('0','NOMBRE INFRAESTRUCTURA','4','22','NOCHE CALIENTE','87','124','20','Datum_B','PLANETA TIERRA',' PRUEBA NOVIEMBRE','1','150302','1',null,null,null,null,null,null,null,'42','82',null,'ORODRIGUEZ',to_date('16/11/21','DD/MM/RR'),'MIPC','FULLSHITO',to_date('16/11/21','DD/MM/RR'),null,'1','MUY ALTO');
